on: 
  workflow_dispatch:
    inputs:
      url:
        description: 'Root URL'
        required: true
        type: string
      pattern:
        description: 'Provide pattern to match children urls'
        required: false
        type: string
  


jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm install -g pa11y-ci
      - run: pa11y-ci --version
      - run: pa11y-ci --no-sandbox ${{ inputs.url }}
 
